// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

type ConnectionType = int8
const (
	ConnectionTypeDirect ConnectionType = 0
	ConnectionTypeBridge ConnectionType = 1
)

var EnumNamesConnectionType = map[ConnectionType]string{
	ConnectionTypeDirect:"Direct",
	ConnectionTypeBridge:"Bridge",
}

