// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

type ConnectionProtocol = int8
const (
	ConnectionProtocolTCP ConnectionProtocol = 0
)

var EnumNamesConnectionProtocol = map[ConnectionProtocol]string{
	ConnectionProtocolTCP:"TCP",
}

