// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

type IDType = int8
const (
	IDTypeUser IDType = 0
	IDTypeAsset IDType = 1
	IDTypeFunction IDType = 2
	IDTypeService IDType = 3
)

var EnumNamesIDType = map[IDType]string{
	IDTypeUser:"User",
	IDTypeAsset:"Asset",
	IDTypeFunction:"Function",
	IDTypeService:"Service",
}

