// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MsgCallRuntimeContent struct {
	_tab flatbuffers.Table
}

func GetRootAsMsgCallRuntimeContent(buf []byte, offset flatbuffers.UOffsetT) *MsgCallRuntimeContent {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MsgCallRuntimeContent{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *MsgCallRuntimeContent) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MsgCallRuntimeContent) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MsgCallRuntimeContent) Caller(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *MsgCallRuntimeContent) CallerLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MsgCallRuntimeContent) CallerBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MsgCallRuntimeContent) MutateCaller(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *MsgCallRuntimeContent) Call(obj *RuntimeCall) *RuntimeCall {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(RuntimeCall)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func MsgCallRuntimeContentStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func MsgCallRuntimeContentAddCaller(builder *flatbuffers.Builder, Caller flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(Caller), 0)
}
func MsgCallRuntimeContentStartCallerVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func MsgCallRuntimeContentAddCall(builder *flatbuffers.Builder, Call flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(Call), 0)
}
func MsgCallRuntimeContentEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
