// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

type MsgType = int8
const (
	MsgTypeQuery MsgType = 0
	MsgTypeToProvider MsgType = 1
	MsgTypeToClient MsgType = 2
	MsgTypeCallRuntime MsgType = 3
	MsgTypePubsubCmd MsgType = 4
	MsgTypePubsubResponse MsgType = 5
	MsgTypeRespond MsgType = 6
)

var EnumNamesMsgType = map[MsgType]string{
	MsgTypeQuery:"Query",
	MsgTypeToProvider:"ToProvider",
	MsgTypeToClient:"ToClient",
	MsgTypeCallRuntime:"CallRuntime",
	MsgTypePubsubCmd:"PubsubCmd",
	MsgTypePubsubResponse:"PubsubResponse",
	MsgTypeRespond:"Respond",
}

