// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

type NodeType = int8
const (
	NodeTypeProvider NodeType = 0
	NodeTypeClient NodeType = 1
)

var EnumNamesNodeType = map[NodeType]string{
	NodeTypeProvider:"Provider",
	NodeTypeClient:"Client",
}

