// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

type PubsubCmd = int8
const (
	PubsubCmdSub PubsubCmd = 0
	PubsubCmdUnsub PubsubCmd = 1
	PubsubCmdPubAll PubsubCmd = 2
	PubsubCmdPubSpec PubsubCmd = 3
	PubsubCmdListTopic PubsubCmd = 4
	PubsubCmdListSubInTopic PubsubCmd = 5
	PubsubCmdWatchTopicSub PubsubCmd = 6
)

var EnumNamesPubsubCmd = map[PubsubCmd]string{
	PubsubCmdSub:"Sub",
	PubsubCmdUnsub:"Unsub",
	PubsubCmdPubAll:"PubAll",
	PubsubCmdPubSpec:"PubSpec",
	PubsubCmdListTopic:"ListTopic",
	PubsubCmdListSubInTopic:"ListSubInTopic",
	PubsubCmdWatchTopicSub:"WatchTopicSub",
}

