// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PubsubCmdResult struct {
	_tab flatbuffers.Table
}

func GetRootAsPubsubCmdResult(buf []byte, offset flatbuffers.UOffsetT) *PubsubCmdResult {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PubsubCmdResult{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *PubsubCmdResult) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PubsubCmdResult) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PubsubCmdResult) Success() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *PubsubCmdResult) MutateSuccess(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *PubsubCmdResult) Content(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *PubsubCmdResult) ContentLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *PubsubCmdResult) ContentBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PubsubCmdResult) MutateContent(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func PubsubCmdResultStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func PubsubCmdResultAddSuccess(builder *flatbuffers.Builder, Success bool) {
	builder.PrependBoolSlot(0, Success, false)
}
func PubsubCmdResultAddContent(builder *flatbuffers.Builder, Content flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(Content), 0)
}
func PubsubCmdResultStartContentVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func PubsubCmdResultEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
