// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

type RuntimeType = int8
const (
	RuntimeTypeJS RuntimeType = 0
	RuntimeTypeWebASM RuntimeType = 1
	RuntimeTypeContainer RuntimeType = 2
)

var EnumNamesRuntimeType = map[RuntimeType]string{
	RuntimeTypeJS:"JS",
	RuntimeTypeWebASM:"WebASM",
	RuntimeTypeContainer:"Container",
}

