// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SchemaVersion struct {
	_tab flatbuffers.Table
}

func GetRootAsSchemaVersion(buf []byte, offset flatbuffers.UOffsetT) *SchemaVersion {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SchemaVersion{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *SchemaVersion) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SchemaVersion) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SchemaVersion) Msg() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 1
}

func (rcv *SchemaVersion) MutateMsg(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *SchemaVersion) Runtime() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 1
}

func (rcv *SchemaVersion) MutateRuntime(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func SchemaVersionStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func SchemaVersionAddMsg(builder *flatbuffers.Builder, Msg int32) {
	builder.PrependInt32Slot(0, Msg, 1)
}
func SchemaVersionAddRuntime(builder *flatbuffers.Builder, Runtime int32) {
	builder.PrependInt32Slot(1, Runtime, 1)
}
func SchemaVersionEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
